apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: de-quilla-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: "true"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
