apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastin-monitor
  namespace: elk-ns
spec:
  version: 8.16.1
  nodeSets:
    - name: galapagos-monitor
      count: 1
      config:
        node.roles: ["master", "data", "ingest"]
        # this might be deprecated
        xpack.monitoring.collection.enabled: true
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: false

  transport:
    tls:
      verificationMode: certificate

  secureSettings:
    - secretName: elk-monitor-user-secret #pragma: allowlist secret
