apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-a
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-a
  template:
    metadata:
      labels:
        app: kafka-producer-a
    spec:
      containers:
        - name: kraken-producer
          image: coffeeisnan/deq-producer:latest
          imagePullPolicy: Always
          command: ["python"]
          args: 
            - "main.py"
            - "--config"
            - "config_a.json"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
