replicas: 1

esJavaOpts: "-Xmx4g -Xms4g"

resources:
  requests:
    cpu: "500"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "3Gi"

volumeClaimTemplate:
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

# 외부 서비스로 노출할 필요 없다면 아래 생략 가능
service:
  type: ClusterIP
