replicaCount: 1

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

env:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-master:9200"

service:
  type: LoadBalancer
  port: 5601

# Optional - pod 배치 제어
nodeSelector: {}
tolerations: []
affinity: {}
