apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mem-map-tweak
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: mem-map-tweak
  template:
    metadata:
      labels:
        name: mem-map-tweak
    spec:
      nodeSelector:
        elasticsearch: enabled
      hostPID: true
      containers:
      - name: sysctl
        image: busybox
        command: ["/bin/sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-sys
          mountPath: /host-sys
          readOnly: false
      volumes:
      - name: host-sys
        hostPath:
          path: /proc/sys
