# name: Pre-Commit Checks

# on:
#   pull_request:
#     branches:
#       - main
#       - dev

# jobs:
#   pre-commit:
#     name: Run Pre-Commit Hooks
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python (for pre-commit)
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11"

#       - name: Install pre-commit
#         run: pip install pre-commit

#       - name: pre-commit install
#         run: pre-commit install

#       - name: Run Pre-Commit Hooks
#         run: pre-commit run --all-files
