# name: Validate Kubernetes Manifests

# on:
#   pull_request:
#     branches:
#       - main
#       - dev

# jobs:
#   validate-yaml:
#     name: Lint YAML and Validate K8s
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install kubeval
#         run: |
#           curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
#           tar xf kubeval-linux-amd64.tar.gz
#           sudo mv kubeval /usr/local/bin/

#       - name: Validate Kubernetes Manifests
#         run: kubeval -d ./k8s --strict
